### ISSUE TITLE
Add healthcheck

### ISSUE THREAD

**Issue by wawrzek** [corda/corda-docker#13]
Add a healthcheck to Corda docker image as discussed in [pull request 11](https://github.com/corda/corda-docker/pull/11).

**Comment by przemolb** [comment]
We need to discuss what is healthy and unhealthy Corda node/networkmap/notary state. As far as I remember it is ambiguous at the moment.

**Comment by wawrzek** [comment]
Please check new docker build from main corda repository: https://github.com/corda/corda/tree/master/docker
