### ISSUE TITLE
any plan to support docker 3.1

### ISSUE THREAD

**Issue by xiaoppp** [corda/corda-docker#21]
For now it still support docker 2.0, so do we have any plan to support the latest docker?
Thanks.

**Comment by xiaoppp** [comment]
@przemolb yes, you are right :)
I know, this is not a big issue, we can replace the dependency and node conf.
But have a official support for docker is really useful for all the corda developers!!!

**Comment by wawrzek** [comment]
Please check new docker build from main corda repository: https://github.com/corda/corda/tree/master/docker
