### ISSUE TITLE
Error log while in container after starting - ($docker start corda12)

### ISSUE THREAD

**Issue by ccPrathap** [corda/corda-docker#6]
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 8
runsv corda: fatal: unable to start ./run: file does not exist
Jul  7 10:36:13 ff7ddf79b0b0 syslog-ng[15]: syslog-ng starting up; version='3.5.6'
runsv corda: fatal: unable to start ./run: file does not exist
runsv corda: fatal: unable to start ./run: file does not exist
runsv corda: fatal: unable to start ./run: file does not exist
runsv corda: fatal: unable to start ./run: file does not exist
runsv corda: fatal: unable to start ./run: file does not exist
runsv corda: fatal: unable to start ./run: file does not exist
runsv corda: fatal: unable to start ./run: file does not exist
runsv corda: fatal: unable to start ./run: file does not exist
runsv corda: fatal: unable to start ./run: file does not exist
runsv corda: fatal: unable to start ./run: file does not exist
runsv corda: fatal: unable to start ./run: file does not exist

**Comment by wawrzek** [comment]
Could you please send commands you used to create docker image?

**Comment by ccPrathap** [comment]
Cloned repo from the master here.
Issued below command

* docker build -t corda:m13 . - to create base Corda image (called corda:m13)
* docker create --env CORDA_CITY=Wroclaw --env CORDA_COUNTRY=Poland --env CORDA_LEGAL_NAME="Very important node" --name corda13 -t corda:m13 - to create configured container based on above (corda:m12) image and called corda13
* docker start corda12 - to start the corda13 container

**Comment by ccPrathap** [comment]
Sorry. Typo. It was 'docker start corda13' only.

**Comment by wawrzek** [comment]
I double check. It's fine for me.

'docker start corda13
corda13'

@ccPrathap - please check your enviornment. What Docker version do you use? OS? 


I'm using:

```Version 17.06.0-ce-mac18 (18433)
Channel: stable
d9b66511e0```

**Comment by ccPrathap** [comment]
I am using Docker Toolbox 1.12.
OS: Windows 7.
I will try with the latest docker version. Hope there won't be any issue.

Thanks.
